### ISSUE TITLE
Onboarding page

### ISSUE THREAD

**Issue by matejthetree** [digitalnomadacademy/youthetree#3]
http://placekitten.com/200/300

Create page that has three inner pages that can be swiped from 1. to 3. 

There is also button `skip` on page 1.2. and on page 3 there is button `start`

<img width="154" alt="Screenshot 2020-04-08 at 18 32 48" src="https://user-images.githubusercontent.com/10059426/78809529-5df4d280-79c7-11ea-8665-bc6b45c983b1.png">

**Comment by Tinjomar** [comment]
I'll try this one.
