### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by matejthetree** [digitalnomadacademy/youthetree#4]
<img width="136" alt="Screenshot 2020-04-08 at 18 35 32" src="https://user-images.githubusercontent.com/10059426/78809831-c8a60e00-79c7-11ea-8ea1-ff4ed1dee9e2.png">

It will have 2 textFields for email or phone.

Under those textfields will be a button for Login

and on the bottom will be button for CreateAccountPage

**Comment by MrgaCRO** [comment]
This is mine
